import { addDays, type ReviewCard } from '@/lib/spaced-repetition';

const now = new Date();

export const initialReviewCards: ReviewCard[] = [
  {
    answer: 'Action potentials open calcium channels at the presynaptic terminal, which triggers neurotransmitter release.',
    course: 'Biology 204',
    difficulty: 7.2,
    dueAt: addDays(now, -0.2).toISOString(),
    id: 'bio-neurotransmitter-release',
    lastReviewedAt: addDays(now, -2.2).toISOString(),
    prompt: 'What triggers neurotransmitter release at a synapse?',
    reviewHistory: [],
    stability: 2.1,
    topic: 'Neural signaling',
  },
  {
    answer: 'Chunking groups separate details into meaningful units, which lowers working-memory load.',
    course: 'Psychology 210',
    difficulty: 4.8,
    dueAt: addDays(now, -0.05).toISOString(),
    id: 'psych-chunking',
    lastReviewedAt: addDays(now, -4).toISOString(),
    prompt: 'Why does chunking help working memory?',
    reviewHistory: [],
    stability: 4.4,
    topic: 'Memory systems',
  },
  {
    answer: 'The chain rule differentiates a composition by multiplying the outer derivative by the inner derivative.',
    course: 'Calculus I',
    difficulty: 6.4,
    dueAt: addDays(now, -0.1).toISOString(),
    id: 'calc-chain-rule',
    lastReviewedAt: addDays(now, -1.6).toISOString(),
    prompt: 'What does the chain rule do?',
    reviewHistory: [],
    stability: 1.7,
    topic: 'Derivative rules',
  },
  {
    answer: 'Primary-source bias is the perspective or limitation built into a firsthand historical source.',
    course: 'Modern History',
    difficulty: 5.6,
    dueAt: addDays(now, 0.8).toISOString(),
    id: 'history-primary-source-bias',
    lastReviewedAt: addDays(now, -3.3).toISOString(),
    prompt: 'What is primary-source bias?',
    reviewHistory: [],
    stability: 5.3,
    topic: 'Source analysis',
  },
  {
    answer: 'Long-term potentiation is a lasting strengthening of synaptic response after repeated activation.',
    course: 'Biology 204',
    difficulty: 7.6,
    dueAt: addDays(now, -0.35).toISOString(),
    id: 'bio-ltp',
    lastReviewedAt: addDays(now, -1.2).toISOString(),
    prompt: 'What does long-term potentiation describe?',
    reviewHistory: [],
    stability: 1.2,
    topic: 'Neural signaling',
  },
  {
    answer: 'Retrieval practice works because it forces active reconstruction and exposes what you cannot recall yet.',
    course: 'Psychology 210',
    difficulty: 4.2,
    dueAt: addDays(now, 1.2).toISOString(),
    id: 'psych-retrieval-practice',
    lastReviewedAt: addDays(now, -2.8).toISOString(),
    prompt: 'Why does retrieval practice beat rereading?',
    reviewHistory: [],
    stability: 6.2,
    topic: 'Memory systems',
  },
];
